name: Modules - Bump Version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github - Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Modules - Version Bump
        uses: paulhatch/semantic-version@v5.2.1
        id: modules
        with:
          change_path: "modules"
          tag_prefix: "modules-v"
          bump_each_commit: false

      - name: Modules - Create tag
        uses: actions/github-script@v6
        if: steps.modules.outputs.changed || 'false' == 'true'
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.modules.outputs.version_tag }}',
              sha: context.sha
            })

      - name: Company-Product - Version Bump
        uses: paulhatch/semantic-version@v5.2.1
        id: company-product
        with:
          change_path: "company-product"
          tag_prefix: "company-product-v"
          bump_each_commit: false

      
      - name: Company-Product - Create tag
        uses: actions/github-script@v6
        if: steps.company-product.outputs.changed || 'false' == 'true'
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.company-product.outputs.version_tag }}',
              sha: context.sha
            })