name: Modules - Bump Version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github - Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Modules - Version Bump
        uses: paulhatch/semantic-version@v5.2.3
        with:
          change_path: "modules"

      - name: Company-Product - Version Bump
        uses: paulhatch/semantic-version@v5.2.3
        with:
          change_path: "company-product"