name: Terraform Apply

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: alpha
      mode:
        type: choice
        default: plan
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    #environment: ${{ inputs.environment }}   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9  # Adjust to the version you need

      - name: Initialize Terraform
        working-directory: ${{ github.workspace }}/environment/${{ inputs.environment }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ github.workspace }}/environment/${{ inputs.environment }}
        run: terraform plan

      - name: Terraform Apply
        if: inputs.mode == 'apply'
        working-directory: ${{ github.workspace }}/environment/${{ inputs.environment }}
        run: terraform apply

      - name: Terraform Destroy
        if: inputs.mode == 'destroy'
        working-directory: ${{ github.workspace }}/environment/${{ inputs.environment }}
        run: terraform apply